load("@build_bazel_rules_swift//swift:swift_library.bzl", "swift_library")
load("//:defs.bzl", "PACKAGE_NAME", "SWIFT_COPTS")

# Layer 3.
swift_library(
    name = "ViewModels",
    srcs = glob(["**/*.swift"]),
    copts = SWIFT_COPTS,
    module_name = "ViewModels",
    package_name = PACKAGE_NAME,
    visibility = [
        "//LCdrData/App:__pkg__",
        "//LCdrData/Views:__pkg__",
        "//LCdrDataTests/AppEnvironment:__pkg__",
        "//LCdrDataTests/ViewModels:__pkg__",
    ],
    deps = [
        "//LCdrData/Core/Models",
        "//LCdrData/Core/Utilities",
        "//LCdrData/Core/Utilities:Formatting",
        "//LCdrData/Services",
    ],
)
